apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-alb
  namespace: kube-system

---

apiVersion: v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
    metadata:
      name: ingress-alb
    rules:
      - apiGroups: ["", "extensions"]
        resources: ["configmaps","endpoints","events","ingresses","ingresses/status"]
        verbs: ["create","get","list","update","watch","patch"]
      - apiGroups: ["", "extensions"]
        resources: ["nodes","pods","secrets","services"]
        verbs: ["get","list","watch"]
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    metadata:
      name: ingress-alb
    subjects:
    - kind: ServiceAccount
      name: ingress-alb
      namespace: kube-system
    roleRef:
      kind: ClusterRole
      name: ingress-alb
      apiGroup: rbac.authorization.k8s.io
kind: List