apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: salutations-deployment
spec:
  replicas: 3
  template:
    metadata:
        labels:
           app: salutations
    spec:
      containers:
      - name: salutations
        image: justatad/salutations_globe
        ports:
          - containerPort: 8080

