apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: salutations-deployment
spec:
  replicas: 3
  template:
    metadata:
        labels:
           app: salutations
    spec:
      containers:
        image: justatad/salutations_globe
        name: salutations
        ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
