apiVersion: apps/v1
kind: Deployment
metadata:
  name: salutations-deployment
  labels:
    app: salutations
spec:
  replicas: 3
  selector:
    matchLabels:
      app: salutations
  template:
    metadata:
        labels:
                app: salutations
    spec:
      containers:
      - name: salutations-globe
        image: justatad/salutations_globe
        ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"

---

kind: Service
apiVersion: apps/v1
metadata:
  name: salutations-service
spec:
  type: NodePort
  selector:
    app: salutations
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
 
 ---
 
apiVersion: apps/v1
kind: Ingress
metadata:
  name: "hello-app-alb-ingress"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: 'subnet-4c50b416, subnet-2ae24862, subnet-719b3e17'
  labels:
    app: salutations
spec:
  rules:
  - host: salutations.zigzag-london.net
  - http:
      paths:
      - path: /
        backend:
          serviceName: "salutations-service"
          servicePort: 80
