apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: salutations-deployment
  labels:
    app: salutations
spec:
  replicas: 2
  selector:
    matchLabels:
      app: salutations
  template:
    metadata:
      labels:
        app: salutations
    spec:
      containers:
      - name: salutations-globe
        image: justatad/salutations_globe
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: salutations-service
spec:
  type: NodePort
  selector:
    app: salutations
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
 
---
 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "hello-app-alb-ingress"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: 'subnet-d1983db7, subnet-ffe04ab7, subnet-1b42a641'
  labels:
    app: salutations
spec:
  rules:
  - host: salutations.cluster.zigzag-london.net
  - http:
      paths:
      - path: /
        backend:
          serviceName: "salutations-service"
          servicePort: 80
